### ISSUE TITLE
Github Token for releasing profiles charts

### ISSUE THREAD

**Issue by steve-fraser** [filecoin-project/gitops-profile-catalog#2]
A Github token needs to be added as an environment to be referenced in a Github Action  

The purpose of the Github token is to automate the release of helm charts for Weave GitOps Enterprise profiles

A Github action will run on a commit to main that will see that there is a new version update in the helm chart it will perform the following actions:
- Create a new release with helm chart
- Update gh-pages branch to add the new version to the index page

**Comment by travisperson** [comment]
I believe GHA automatically are provisioned a token when they run: [Automatic Token Authentication](https://docs.github.com/en/actions/security-guides/automatic-token-authentication).

I just looked at a marketplace action for publishing releases and their documentation:
> If publishing on the same repo that runs the workflow, the automatically created token ${{ secrets.GITHUB_TOKEN }} should work. 
https://github.com/marketplace/actions/publish-a-release#inputs

I'm also pretty sure this default token will have writes to push branch, particularly gh-pages branches:
> By default, the action does not need any token configuration and uses the provided repository scoped GitHub token to make the deployment.
https://github.com/marketplace/actions/deploy-to-github-pages

I think we should try to set this up with the default token. if we run into issues we can come back here and setup a token from our service account filecoin-helper.

An issue we may face is if we are using the `restricted` token: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

See also: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#how-the-permissions-are-calculated-for-a-workflow-job

**Comment by steve-fraser** [comment]
Token not required to perform action
